// Datos de ejemplo para el inventario
export const inventoryData = [
  {
    name: "Paracetamol 500mg",
    lot: "PAR-2023-001",
    quantity: 500,
    expiryDate: "2025-06-30",
    status: "Disponible",
    warehouse: "Principal",
    origin: "Migración inicial",
  },
  {
    name: "Ibuprofeno 400mg",
    lot: "IBU-2023-002",
    quantity: 300,
    expiryDate: "2025-04-15",
    status: "Disponible",
    warehouse: "Principal",
    origin: "Migración inicial",
  },
  {
    name: "Amoxicilina 500mg",
    lot: "AMO-2023-003",
    quantity: 200,
    expiryDate: "2024-12-10",
    status: "Disponible",
    warehouse: "Principal",
    origin: "Migración inicial",
  },
  {
    name: "Omeprazol 20mg",
    lot: "OME-2023-004",
    quantity: 150,
    expiryDate: "2025-02-20",
    status: "Disponible",
    warehouse: "Secundario",
    origin: "Migración inicial",
  },
  {
    name: "Loratadina 10mg",
    lot: "LOR-2023-005",
    quantity: 250,
    expiryDate: "2024-08-05",
    status: "Disponible",
    warehouse: "Principal",
    origin: "Migración inicial",
  },
  {
    name: "Solución Salina 0.9%",
    lot: "SOL-2023-006",
    quantity: 100,
    expiryDate: "2025-01-15",
    status: "Disponible",
    warehouse: "Emergencia",
    origin: "Migración inicial",
  },
  {
    name: "Metformina 850mg",
    lot: "MET-2023-007",
    quantity: 180,
    expiryDate: "2024-11-30",
    status: "Disponible",
    warehouse: "Principal",
    origin: "Migración inicial",
  },
  {
    name: "Enalapril 10mg",
    lot: "ENA-2023-008",
    quantity: 120,
    expiryDate: "2024-07-25",
    status: "Por vencer",
    warehouse: "Principal",
    origin: "Migración inicial",
  },
  {
    name: "Atorvastatina 20mg",
    lot: "ATO-2023-009",
    quantity: 90,
    expiryDate: "2024-09-18",
    status: "Disponible",
    warehouse: "Secundario",
    origin: "Migración inicial",
  },
  {
    name: "Diclofenaco 50mg",
    lot: "DIC-2023-010",
    quantity: 0,
    expiryDate: "2024-10-05",
    status: "Agotado",
    warehouse: "Principal",
    origin: "Migración inicial",
  },
]

